import { tv } from '@heroui/theme';

export const accordionItemLinkVariants = tv({
  base: [
    "text-sideBarText hover:text-primary",
    "border-sideBarText hover:border-primary",
    "hover:md:bg-primary/10 xl:hover:bg-transparent",
    "xl:hover:bg-gradient-to-r from-gray-200 to-gray-900]",
    "rounded-xl xl:rounded-none",
    "transition-all",
    "duration-500",
    "ease-linear",
    "font-medium",
    "inline-block",
    "py-3.5 md:py-[1.125rem]",
    "px-6 md:px-3.5",
    "text-[0.9375rem] 2xl:text-base",
    "relative",
    "md:text-center",
    'xl:before:content-[""]',
    "xl:before:h-[4.68rem]",
    "xl:before:w-0",
    "xl:before:absolute",
    "xl:before:left-0",
    "xl:before:top-2/4",
    "xl:before:-translate-y-2/4",
    "xl:before:bg-primary",
    "xl:before:rounded-e-xl",
    "xl:before:transition-all",
    "xl:before:duration-500",
    "xl:hover:before:w-2.5",
    "after:absolute",
    'after:content-[""]',
    "after:w-2",
    "after:h-2",
    "after:right-[1.875rem]",
    "after:top-[48%]",
    "after:rotate-[-225deg]",
    "after:-translate-y-2/4",
    "after:border-t",
    "after:border-l",
    "after:border-solid",
    "after:border-inherit",
    "after:transition-all",
    "after:ease-out",
    "after:duration-300",
    "after:md:hidden",
  ],
  variants: {
    opened: {
      true: [
        "after:rotate-[-135deg]",
        "text-primary",
        "border-primary",
        "bg-primary/10 xl:bg-transparent",
        "xl:bg-gradient-to-r from-gray-200 to-gray-900]",
        "xl:before:w-2.5",
      ],
      false: "",
    },
    active: {
      true: "text-primary",
      false: "",
    },
    hideArrow: {
      true: "after:hidden",
    },
  },
});
